name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy-gh-pages:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Create 404.html file
        run: |
          mkdir build
          cat > build/404.html <<EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Slim</title>
              <script type="text/javascript">
                var numPathSegmentsToKeep = 1;
                var l = window.location;
                l.replace(
                  l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
                  l.pathname.split('/').slice(0, 1 + numPathSegmentsToKeep).join('/') + '/?/' +
                  l.pathname.slice(1).split('/').slice(numPathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
                  (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
                  l.hash
                );
              </script>
            </head>
            <body>
            </body>
          </html>
          EOF
      - name: Build and deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
